Updated ESLint Workflow

diff --git a/.github/workflows/eslint.yml b/.github/workflows/eslint.yml
--- a/.github/workflows/eslint.yml
+++ b/.github/workflows/eslint.yml
@@ -17,8 +17,9 @@ jobs:
       - name: Install dependencies
         run: npm ci
       - name: Run ESLint Checks
-        run: npx eslint . --ext .js,.jsx,.ts,.tsx --fix-all --max-warnings 0
+        run: |
+          npx eslint . --ext .js,.jsx,.ts,.tsx --fix-all --max-warnings 0
           if [ $? -ne 0 ]; then
-          echo "ESLint errors found. Please fix before merging."
-          exit 1
+            echo "ESLint errors found. Please fix before merging."
+            exit 1
           fi
