Updated prettier-workflow

diff --git a/.github/workflows/prettier.yml b/.github/workflows/prettier.yml
--- a/.github/workflows/prettier.yml
+++ b/.github/workflows/prettier.yml
@@ -14,5 +14,9 @@ jobs:
       - uses: actions/setup-node@v4
         with:
           node-version: 20
-      - name: Check style
-        run: npx prettier . --check
+      - name: Install dependencies
+        run: npm ci
+      - name: Check and fix style
+        run: npx prettier --write . || (echo "Prettier failed to fix style issues. Check logs for details." && exit 1)
+      - name: Check for remaining issues
+        run: npx prettier --check . || (echo "Prettier check failed. Check logs for details." && exit 1)
